### ISSUE TITLE
UI Flicker when closing Store Modal Popup

### ISSUE THREAD

**Issue by albatrosify** [akshaynjarangal/appstore_info#1]
Hey,

I do notice some flickering when I use the "done" button on the presented appstore modal.
It also happens, when I tap outside. Seems like it momentarily switches to full-screen and then back to the correct size and animates the close-animation...

Any idea how to fix this?

EDIT: 
I've tried this on iPad

**Comment by akshaynjarangal** [comment]
Hi 👋 @albatrosify , thanks for the issue reporting , can you share the screen record and which iPadOS version are you using?

**Comment by albatrosify** [comment]
Thanks for your quick reply :) 
Here you go: 

https://github.com/akshaynjarangal/appstore_info/assets/64252708/4365a5cd-0787-4b3b-8059-e5b1790815f8
Freeze-Frame:
<img width="1261" alt="Bildschirmfoto 2024-06-05 um 10 33 55" src="https://github.com/akshaynjarangal/appstore_info/assets/64252708/0f7c8058-061d-4f17-a26a-17e028af9eb1">

**Comment by albatrosify** [comment]
Very nice :) I can confirm this has been fixed. Thanks a lot for the excellent package!

**Comment by akshaynjarangal** [comment]
You're welcome! @albatrosify 🤗, I'm glad to hear that everything is working well for you now , Thank you for the kind words! 😍, please share this plugin to your area developer community
